// src/app/api/testimonials/route.js
import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import Testinomial from "@/models/Testinomials";
import User from "@/models/User";
import sendMail from "@/lib/sendMail";

export async function GET() {
  try {
    await connectDB();
    const tmp = await Testinomial.find().sort({ createdAt: -1 });
    return NextResponse.json(tmp);
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { error: "Internal server error!" },
      { status: 500 }
    );
  }
}

export async function POST(req) {
  try {
    await connectDB();
    const user = await verifyAdmin();
    if (!user || user.role !== "admin") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const body = await req.json();
    const testimonial = await Testinomial.create(body);

    //Mail
    const prevAdmins = await User.find({
      role: "admin",
      _id: { $ne: user._id },
    });
    const emails = prevAdmins.map((U) => U.email);

    if (emails.length > 0) {
      const html = `<p>A testimonial comment was created by ${user.name} in code<font color='red'>N</font>ergy</p>
                    <p><b>New comment</b><br />Name: ${testimonial.name}<br />Role: ${testimonial.role}<br />Comment: ${testimonial.comment}</p>
                    <p>This mail is auto generated by code<font color='red'>N</font>ergy system so please dont reply </p>
                    `;
      await sendMail({ to: emails, subject: "New User Created", html });
    }
    return NextResponse.json(testimonial, { status: 201 });
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { error: "Failed to create testimonial" },
      { status: 500 }
    );
  }
}
