import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import Appointment from "@/models/Appointment";
import Service from "@/models/Services";
import User from "@/models/User";
import { verifyAdmin } from "@/lib/verifyToken";
import sendMail from "@/lib/sendMail";
import Activities from "@/models/Activities";

export async function GET() {
  try {
    await connectDB();
    const user = await verifyAdmin();
    if (!user || user.role !== "admin") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const appointments = await Appointment.find().populate(
      "serviceId",
      "title"
    );
    return NextResponse.json(appointments, { status: 200 });
  } catch (err) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(req) {
  try {
    await connectDB();
    const body = await req.json();
    const newAppointment = await Appointment.create(body);
    await Activities.create({
      content: `A new appointment has been scheduled by ${body.name}`,
    });
    const prevAdmins = await User.find({
      role: "admin",
    });
    const emails = prevAdmins.map((U) => U.email);

    if (emails.length > 0) {
      const html = `
      <p>Hey, we have a new appointment scheduled by a client on code<font color='red'>N</font>ergy website, please check the website admin panel as soon as possible</p>
      <p>This mail is auto generated by code<font color='red'>N</font>ergy system so please dont reply </p>
                    `;
      await sendMail({
        to: emails,
        subject: "Appointment scheduled by a client",
        html,
      });
    }
    return NextResponse.json(newAppointment, { status: 201 });
  } catch (err) {
    return NextResponse.json({ error: err.message }, { status: 400 });
  }
}
