import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import User from "@/models/User";
import { verifyAdmin } from "@/lib/verifyToken";
import bcrypt from "bcryptjs";
import sendMail from "@/lib/sendMail";

// ✅ GET All Users
export async function GET() {
  await connectDB();
  const user = await verifyAdmin();
  if (!user || user.role !== "admin") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const users = await User.find().sort({ createdAt: -1 });
  return NextResponse.json(users);
}

// ✅ CREATE New User (same logic as createUser route)
export async function POST(req) {
  await connectDB();
  const user = await verifyAdmin();
  if (!user || user.role !== "admin") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { name, email, password, role } = await req.json();
  if (!name || !email || !password)
    return NextResponse.json({ error: "All fields required" }, { status: 400 });

  // Check email
  const exists = await User.findOne({ email });
  if (exists)
    return NextResponse.json(
      { error: "Email already exists" },
      { status: 400 }
    );

  const hashedPassword = await bcrypt.hash(password, 10);
  const validRoles = ["user", "admin"];
  const userRole = validRoles.includes(role) ? role : "user";

  const newUser = await User.create({
    name,
    email,
    password: hashedPassword,
    role: userRole,
  });

  // Notify other admins
  const prevAdmins = await User.find({ role: "admin", _id: { $ne: user._id } });
  const emails = prevAdmins.map((U) => U.email);

  if (emails.length > 0) {
    const html = `<p>A new user was created by ${user.name} in code<font color='red'>N</font>ergy</p>
                  <p><b>New User</b><br />Name: ${newUser.name}<br />Email: ${newUser.email}<br />Role: ${newUser.role}</p>
                  <p>This mail is auto generated by code<font color='red'>N</font>ergy system so please dont reply </p>
                  `;
    await sendMail({ to: emails, subject: "New User Created", html });
  }

  return NextResponse.json(newUser, { status: 201 });
}
