import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import User from "@/models/User";
import sendMail from "@/lib/sendMail";
import { verifyAdmin } from "@/lib/verifyToken";

// ✅ DELETE
export async function DELETE(req, context) {
  await connectDB();
  const user = await verifyAdmin();
  const { id } = await context.params;
  if (!user || user.role !== "admin") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const deleted = await User.findByIdAndDelete(id);
  const prevAdmins = await User.find({ role: "admin", _id: { $ne: user._id } });
  const emails = prevAdmins.map((U) => U.email);

  if (emails.length > 0) {
    const html = `<p>A user is deleted by ${user.name} in code<font color='red'>N</font>ergy</p>
                  <p><b>Deleted User</b><br />Name: ${deleted.name}<br />Email: ${deleted.email}<br />Role: ${deleted.role}</p>
                  <p>This mail is auto generated by code<font color='red'>N</font>ergy system so please dont reply </p>
                  `;
    await sendMail({ to: emails, subject: "User deleted!", html });
  }
  if (!deleted)
    return NextResponse.json({ error: "User not found" }, { status: 404 });
  return NextResponse.json({ message: "User deleted successfully" });
}

// ✅ UPDATE Role
export async function PUT(req, context) {
  await connectDB();
  const user = await verifyAdmin();
  if (!user || user.role !== "admin") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const { id } = await context.params;

  const { role } = await req.json();
  const updated = await User.findByIdAndUpdate(id, { role }, { new: true });
  if (!updated)
    return NextResponse.json({ error: "User not found" }, { status: 404 });
  return NextResponse.json(updated);
}
