import { connectDB } from "@/lib/mongodb";
import { verifyAdmin } from "@/lib/verifyToken";
import Message from "@/models/Messages";
import User from "@/models/User";
import sendMail from "@/lib/sendMail";
import { NextResponse } from "next/server";
export async function GET() {
  try {
    await connectDB();
    const user = await verifyAdmin();
    if (!user || user.role !== "admin") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const message = await Message.find().sort({ createdAt: -1 });

    return NextResponse.json(message, { status: 200 });
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { error: "Server error, please contact to admin!" },
      { status: 500 }
    );
  }
}

export async function POST(req) {
  await connectDB();
  let { name, email, message } = await req.json();
  console.log(name, email, message);
  message.trim();
  if ((!name, !email, !message)) {
    return NextResponse.json(
      { message: "Please send complete data" },
      { status: 400 }
    );
  }
  try {
    let msg = Message({ name, email, message });
    await msg.save();
    const prevAdmins = await User.find({ role: "admin" });
    const emails = prevAdmins.map((U) => U.email);

    if (emails.length > 0) {
      const html = `
      <p>Hey, we have a new message on code<font color='red'>N</font>ergy website, please visit the admin panel of the code<font color='red'>N</font>ergy website as soon as possible.</p>
      <p>This mail is auto generated by code<font color='red'>N</font>ergy system so please dont reply </p>
                    `;
      await sendMail({
        to: emails,
        subject: "Message on codeNergy website",
        html,
      });
    }

    return NextResponse.json(
      { message: "Message created successfully!!!" },
      { status: 200 }
    );
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { message: "Internal server error!" },
      { status: 500 }
    );
  }
}
